# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcus', '0003_remotecamera_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='s3_location',
            new_name='url',
        ),
    ]
